### ISSUE TITLE
t/01_all.t fails if Text::Table::Simple isn't installed

### ISSUE THREAD

**Issue by timo** [nkh/P6-Data-Dump-Tree#11]
It requires a specific number of lines in the output, but if TTS isn't installed, there's an exception output in there that will vary its length depending on what's in your -I and repos in general.

**Comment by nkh** [comment]
Right, that should be removed. There is an all.pl in the examples directory. DDT handles the error but the test is unaware of that.

I need to check if there is a 'No' module to remove modules while testing.
