### ISSUE TITLE
Could not find Data::Dump::Tree::RemoteFoldObject

### ISSUE THREAD

**Issue by frithnanth** [nkh/P6-Data-Dump-Tree#35]
Hi,

I tried to install Data::Dump::Tree using zef, on a clean rakudo installation and I get this error message:

===> Install [FAIL] for Data::Dump::Tree:ver('1.7.0'):auth('github:nkh'): ===SORRY!===
Could not find Data::Dump::Tree::RemoteFoldObject at line 87 in:
    /opt/rakudo/share/perl6/site
    /opt/rakudo/share/perl6/vendor
    /opt/rakudo/share/perl6
    CompUnit::Repository::AbsolutePath<94416879887696>
    CompUnit::Repository::NQP<94416880206432>
    CompUnit::Repository::Perl5<94416880206472>

===SORRY!===
Could not find Data::Dump::Tree::RemoteFoldObject at line 87 in:
    /opt/rakudo/share/perl6/site
    /opt/rakudo/share/perl6/vendor
    /opt/rakudo/share/perl6
    CompUnit::Repository::AbsolutePath<94416879887696>
    CompUnit::Repository::NQP<94416880206432>
    CompUnit::Repository::Perl5<94416880206472>

  in any  at /opt/rakudo/share/perl6/precomp/1049D337DEF3307152AD072D6367A639E427DB18.1503406667.04303/A5/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 line 1
  in block  at /opt/rakudo/share/perl6/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 581
  in any  at /opt/rakudo/share/perl6/precomp/1049D337DEF3307152AD072D6367A639E427DB18.1503406667.04303/A5/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 line 1
  in block  at /opt/rakudo/share/perl6/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 589
  in block  at /opt/rakudo/share/perl6/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 552
  in sub  at /opt/rakudo/share/perl6/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 541
  in method install at /opt/rakudo/share/perl6/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 633
  in sub MAIN at /opt/rakudo/share/perl6/sources/31FF9E8498781BF95868DF98AD861FCF1211BCC1 (Zef::CLI) line 152
  in block <unit> at /opt/rakudo/share/perl6/resources/0031ECC6124802A80F7B7B073C50D0A1694E3020 line 1
  in sub MAIN at /opt/rakudo/bin/zef line 2
  in block <unit> at /opt/rakudo/bin/zef line 2

**Comment by nkh** [comment]
I uploaded a version an hour ago that should have fixed that, did you install with the latest version?

**Comment by frithnanth** [comment]
Thank you, now it works!
