### ISSUE TITLE
num64.new does not create a num64

### ISSUE THREAD

**Issue by zoffixznet** [nkh/P6-Data-Dump-Tree#42]
There are several instances of `num64.new` in this codebase (e.g [here](https://github.com/nkh/P6-Data-Dump-Tree/blob/a0374d5355253419a633151faa7e277172b570fc/examples/int32.pl#L32)) and that's an error.

It returns a `Num` and currently it's silently failing in this way, but will die on newer rakudos.

The proper way to construct a `num64` would be using `(my num64 $ = 888e0)` instead, though in your uses you can likely just rely on auto-unboxing and use plain `888e0`

**Comment by zoffixznet** [comment]
@nkh ping. The deprecation period already expired and the module is now uninstallable. There's a PR fixing the issue: https://github.com/nkh/P6-Data-Dump-Tree/pull/44

**Comment by nkh** [comment]
Gave had zero time lately. thanks for the reminder
