### ISSUE TITLE
Bags can not be shown with DDT

### ISSUE THREAD

**Issue by lizmat** [nkh/P6-Data-Dump-Tree#53]
$ perl6 -e 'use Data::Dump::Tree; ddt <a b c>.Bag'
    Too many positionals passed; expected 2 arguments but got 3
      in method get_element_header at /Users/liz/Github/rakudo.moar/install/share/perl6/site/sources/25FB865044D56971153B54ECAC0E0CF89CA24FF5 (Data::Dump::Tree) line 517
      in method render_root at /Users/liz/Github/rakudo.moar/install/share/perl6/site/sources/25FB865044D56971153B54ECAC0E0CF89CA24FF5 (Data::Dump::Tree) line 229
      in method get_dump_lines at /Users/liz/Github/rakudo.moar/install/share/perl6/site/sources/25FB865044D56971153B54ECAC0E0CF89CA24FF5 (Data::Dump::Tree) line 167
      in method get_dump at /Users/liz/Github/rakudo.moar/install/share/perl6/site/sources/25FB865044D56971153B54ECAC0E0CF89CA24FF5 (Data::Dump::Tree) line 135
      in sub get_dump at /Users/liz/Github/rakudo.moar/install/share/perl6/site/sources/25FB865044D56971153B54ECAC0E0CF89CA24FF5 (Data::Dump::Tree) line 114
      in sub ddt at /Users/liz/Github/rakudo.moar/install/share/perl6/site/sources/25FB865044D56971153B54ECAC0E0CF89CA24FF5 (Data::Dump::Tree) line 110
      in block <unit> at -e line 1

**Comment by nkh** [comment]
fixed in d96afdc
