### ISSUE TITLE
Slips are not handled correctly

### ISSUE THREAD

**Issue by lizmat** [nkh/P6-Data-Dump-Tree#54]
$ perl6 -e 'use Data::Dump::Tree; ddt (1,2,3).Slip'
    1

**Comment by nkh** [comment]
Implemented as a special case by wrapping Slips in Data::Dump::Tree::Type::SlipWrapper, Another attempt, handling the Slip as an object as long as possible before passing it in  a list, had too large an impact on the code base.

**Comment by lizmat** [comment]
FWIW, `Slip`s need special handling throughout the Rakudo code base to give them their magical properties.

**Comment by nkh** [comment]
It made me crazy, once I got it to display properly I found it that the changes broke everything else, I didn't have enough tests to find the errors, running the examples in the distribution, which unfortunately don't all have corresponding tests,  showed that even making a diff between two data structures was broken (my favorite part of DDT).

10 lines  to handle Slip, and everything works like before, not sure if a hack like that shouldn't be called the best solution.

Thank you for reporting it, maybe ;), I am not sure how many people need to render Slips.

**Comment by lizmat** [comment]
I needed it because I have a large array of arrays and hashes and wanted a cheap way of making it object oriented.  So I have a role that you just like the keys, and it will automatically create methods for that accessing that key in the hash (very much like standard Perl 5 objects).  The problem was with the arrays, because they got itemized.  This meant you couldn't do `for $obj.array", because it wouldn't iterate.  But it *does* if you bind the key to a `Slip`  :-)   Which is a bit of a hack, but it works really nicely and smoothly  :-)

**Comment by nkh** [comment]
An example of the data structure, what you wanted to do with it and how the Slips where used would make a nice technical article for many I think.

**Comment by lizmat** [comment]
The thought has crossed my mind

**Comment by nkh** [comment]
If you write an article, I need to see more of P6 usage,  and do dumps with DDT, let me know if you want some help with filters if the wrap_highlight example is not enough, or  a review.

for presentation, and quite often for oneself too, :flat(0) can give  a nicer/more usable display, even if it is slooooow.
