### ISSUE TITLE
very fragile tests

### ISSUE THREAD

**Issue by timo** [nkh/P6-Data-Dump-Tree#9]
I was trying to fix DDTree for changes to how lexical require is handled[1] but tests fail in absolutely nebulous ways. The number of lines doesn't equal the expected number of lines, but how am I supposed to spot if things are wrong or right without something to actually compare against?

[1] http://rakudo.org/2017/03/18/lexical-require-upgrade-info/

**Comment by nkh** [comment]
Can you send me the fixes you tried to implement?

**Comment by timo** [comment]
it's in #10

**Comment by nkh** [comment]
OK, I close this and will pull your commit.
